// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ArgusWatcherListerExpansion allows custom methods to be added to
// ArgusWatcherLister.
type ArgusWatcherListerExpansion interface{}

// ArgusWatcherNamespaceListerExpansion allows custom methods to be added to
// ArgusWatcherNamespaceLister.
type ArgusWatcherNamespaceListerExpansion interface{}
