// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/clustergarage/fim-k8s/pkg/client/clientset/versioned/typed/fimcontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFimcontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFimcontrollerV1alpha1) FimWatches(namespace string) v1alpha1.FimWatchInterface {
	return &FakeFimWatches{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFimcontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
