// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/clustergarage/fim-k8s/pkg/apis/fimcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFimWatches implements FimWatchInterface
type FakeFimWatches struct {
	Fake *FakeFimcontrollerV1alpha1
	ns   string
}

var fimwatchesResource = schema.GroupVersionResource{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Resource: "fimwatches"}

var fimwatchesKind = schema.GroupVersionKind{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Kind: "FimWatch"}

// Get takes name of the fimWatch, and returns the corresponding fimWatch object, and an error if there is any.
func (c *FakeFimWatches) Get(name string, options v1.GetOptions) (result *v1alpha1.FimWatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fimwatchesResource, c.ns, name), &v1alpha1.FimWatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatch), err
}

// List takes label and field selectors, and returns the list of FimWatches that match those selectors.
func (c *FakeFimWatches) List(opts v1.ListOptions) (result *v1alpha1.FimWatchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fimwatchesResource, fimwatchesKind, c.ns, opts), &v1alpha1.FimWatchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FimWatchList{ListMeta: obj.(*v1alpha1.FimWatchList).ListMeta}
	for _, item := range obj.(*v1alpha1.FimWatchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fimWatches.
func (c *FakeFimWatches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fimwatchesResource, c.ns, opts))

}

// Create takes the representation of a fimWatch and creates it.  Returns the server's representation of the fimWatch, and an error, if there is any.
func (c *FakeFimWatches) Create(fimWatch *v1alpha1.FimWatch) (result *v1alpha1.FimWatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fimwatchesResource, c.ns, fimWatch), &v1alpha1.FimWatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatch), err
}

// Update takes the representation of a fimWatch and updates it. Returns the server's representation of the fimWatch, and an error, if there is any.
func (c *FakeFimWatches) Update(fimWatch *v1alpha1.FimWatch) (result *v1alpha1.FimWatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fimwatchesResource, c.ns, fimWatch), &v1alpha1.FimWatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatch), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFimWatches) UpdateStatus(fimWatch *v1alpha1.FimWatch) (*v1alpha1.FimWatch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fimwatchesResource, "status", c.ns, fimWatch), &v1alpha1.FimWatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatch), err
}

// Delete takes name of the fimWatch and deletes it. Returns an error if one occurs.
func (c *FakeFimWatches) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fimwatchesResource, c.ns, name), &v1alpha1.FimWatch{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFimWatches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fimwatchesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FimWatchList{})
	return err
}

// Patch applies the patch and returns the patched fimWatch.
func (c *FakeFimWatches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fimwatchesResource, c.ns, name, data, subresources...), &v1alpha1.FimWatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatch), err
}
