// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "clustergarage.io/fim-k8s/pkg/apis/fimcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFimListeners implements FimListenerInterface
type FakeFimListeners struct {
	Fake *FakeFimcontrollerV1alpha1
	ns   string
}

var fimlistenersResource = schema.GroupVersionResource{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Resource: "fimlisteners"}

var fimlistenersKind = schema.GroupVersionKind{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Kind: "FimListener"}

// Get takes name of the fimListener, and returns the corresponding fimListener object, and an error if there is any.
func (c *FakeFimListeners) Get(name string, options v1.GetOptions) (result *v1alpha1.FimListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fimlistenersResource, c.ns, name), &v1alpha1.FimListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimListener), err
}

// List takes label and field selectors, and returns the list of FimListeners that match those selectors.
func (c *FakeFimListeners) List(opts v1.ListOptions) (result *v1alpha1.FimListenerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fimlistenersResource, fimlistenersKind, c.ns, opts), &v1alpha1.FimListenerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FimListenerList{ListMeta: obj.(*v1alpha1.FimListenerList).ListMeta}
	for _, item := range obj.(*v1alpha1.FimListenerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fimListeners.
func (c *FakeFimListeners) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fimlistenersResource, c.ns, opts))

}

// Create takes the representation of a fimListener and creates it.  Returns the server's representation of the fimListener, and an error, if there is any.
func (c *FakeFimListeners) Create(fimListener *v1alpha1.FimListener) (result *v1alpha1.FimListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fimlistenersResource, c.ns, fimListener), &v1alpha1.FimListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimListener), err
}

// Update takes the representation of a fimListener and updates it. Returns the server's representation of the fimListener, and an error, if there is any.
func (c *FakeFimListeners) Update(fimListener *v1alpha1.FimListener) (result *v1alpha1.FimListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fimlistenersResource, c.ns, fimListener), &v1alpha1.FimListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimListener), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFimListeners) UpdateStatus(fimListener *v1alpha1.FimListener) (*v1alpha1.FimListener, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fimlistenersResource, "status", c.ns, fimListener), &v1alpha1.FimListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimListener), err
}

// Delete takes name of the fimListener and deletes it. Returns an error if one occurs.
func (c *FakeFimListeners) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fimlistenersResource, c.ns, name), &v1alpha1.FimListener{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFimListeners) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fimlistenersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FimListenerList{})
	return err
}

// Patch applies the patch and returns the patched fimListener.
func (c *FakeFimListeners) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fimlistenersResource, c.ns, name, data, subresources...), &v1alpha1.FimListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimListener), err
}
