// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "clustergarage.io/fim-k8s/pkg/apis/fimcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFimWatchers implements FimWatcherInterface
type FakeFimWatchers struct {
	Fake *FakeFimcontrollerV1alpha1
	ns   string
}

var fimwatchersResource = schema.GroupVersionResource{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Resource: "fimwatchers"}

var fimwatchersKind = schema.GroupVersionKind{Group: "fimcontroller.clustergarage.io", Version: "v1alpha1", Kind: "FimWatcher"}

// Get takes name of the fimWatcher, and returns the corresponding fimWatcher object, and an error if there is any.
func (c *FakeFimWatchers) Get(name string, options v1.GetOptions) (result *v1alpha1.FimWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fimwatchersResource, c.ns, name), &v1alpha1.FimWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatcher), err
}

// List takes label and field selectors, and returns the list of FimWatchers that match those selectors.
func (c *FakeFimWatchers) List(opts v1.ListOptions) (result *v1alpha1.FimWatcherList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fimwatchersResource, fimwatchersKind, c.ns, opts), &v1alpha1.FimWatcherList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FimWatcherList{ListMeta: obj.(*v1alpha1.FimWatcherList).ListMeta}
	for _, item := range obj.(*v1alpha1.FimWatcherList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fimWatchers.
func (c *FakeFimWatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fimwatchersResource, c.ns, opts))

}

// Create takes the representation of a fimWatcher and creates it.  Returns the server's representation of the fimWatcher, and an error, if there is any.
func (c *FakeFimWatchers) Create(fimWatcher *v1alpha1.FimWatcher) (result *v1alpha1.FimWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fimwatchersResource, c.ns, fimWatcher), &v1alpha1.FimWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatcher), err
}

// Update takes the representation of a fimWatcher and updates it. Returns the server's representation of the fimWatcher, and an error, if there is any.
func (c *FakeFimWatchers) Update(fimWatcher *v1alpha1.FimWatcher) (result *v1alpha1.FimWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fimwatchersResource, c.ns, fimWatcher), &v1alpha1.FimWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatcher), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFimWatchers) UpdateStatus(fimWatcher *v1alpha1.FimWatcher) (*v1alpha1.FimWatcher, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fimwatchersResource, "status", c.ns, fimWatcher), &v1alpha1.FimWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatcher), err
}

// Delete takes name of the fimWatcher and deletes it. Returns an error if one occurs.
func (c *FakeFimWatchers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fimwatchersResource, c.ns, name), &v1alpha1.FimWatcher{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFimWatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fimwatchersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FimWatcherList{})
	return err
}

// Patch applies the patch and returns the patched fimWatcher.
func (c *FakeFimWatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fimwatchersResource, c.ns, name, data, subresources...), &v1alpha1.FimWatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FimWatcher), err
}
