// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FimWatchListerExpansion allows custom methods to be added to
// FimWatchLister.
type FimWatchListerExpansion interface{}

// FimWatchNamespaceListerExpansion allows custom methods to be added to
// FimWatchNamespaceLister.
type FimWatchNamespaceListerExpansion interface{}
