// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FimListenerListerExpansion allows custom methods to be added to
// FimListenerLister.
type FimListenerListerExpansion interface{}

// FimListenerNamespaceListerExpansion allows custom methods to be added to
// FimListenerNamespaceLister.
type FimListenerNamespaceListerExpansion interface{}
