// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FimWatcherListerExpansion allows custom methods to be added to
// FimWatcherLister.
type FimWatcherListerExpansion interface{}

// FimWatcherNamespaceListerExpansion allows custom methods to be added to
// FimWatcherNamespaceLister.
type FimWatcherNamespaceListerExpansion interface{}
