// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "clustergarage.io/argus-controller/pkg/apis/arguscontroller/v1alpha1"
	scheme "clustergarage.io/argus-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArgusWatchersGetter has a method to return a ArgusWatcherInterface.
// A group's client should implement this interface.
type ArgusWatchersGetter interface {
	ArgusWatchers(namespace string) ArgusWatcherInterface
}

// ArgusWatcherInterface has methods to work with ArgusWatcher resources.
type ArgusWatcherInterface interface {
	Create(*v1alpha1.ArgusWatcher) (*v1alpha1.ArgusWatcher, error)
	Update(*v1alpha1.ArgusWatcher) (*v1alpha1.ArgusWatcher, error)
	UpdateStatus(*v1alpha1.ArgusWatcher) (*v1alpha1.ArgusWatcher, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ArgusWatcher, error)
	List(opts v1.ListOptions) (*v1alpha1.ArgusWatcherList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArgusWatcher, err error)
	ArgusWatcherExpansion
}

// argusWatchers implements ArgusWatcherInterface
type argusWatchers struct {
	client rest.Interface
	ns     string
}

// newArgusWatchers returns a ArgusWatchers
func newArgusWatchers(c *ArguscontrollerV1alpha1Client, namespace string) *argusWatchers {
	return &argusWatchers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the argusWatcher, and returns the corresponding argusWatcher object, and an error if there is any.
func (c *argusWatchers) Get(name string, options v1.GetOptions) (result *v1alpha1.ArgusWatcher, err error) {
	result = &v1alpha1.ArgusWatcher{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("arguswatchers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ArgusWatchers that match those selectors.
func (c *argusWatchers) List(opts v1.ListOptions) (result *v1alpha1.ArgusWatcherList, err error) {
	result = &v1alpha1.ArgusWatcherList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("arguswatchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested argusWatchers.
func (c *argusWatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("arguswatchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a argusWatcher and creates it.  Returns the server's representation of the argusWatcher, and an error, if there is any.
func (c *argusWatchers) Create(argusWatcher *v1alpha1.ArgusWatcher) (result *v1alpha1.ArgusWatcher, err error) {
	result = &v1alpha1.ArgusWatcher{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("arguswatchers").
		Body(argusWatcher).
		Do().
		Into(result)
	return
}

// Update takes the representation of a argusWatcher and updates it. Returns the server's representation of the argusWatcher, and an error, if there is any.
func (c *argusWatchers) Update(argusWatcher *v1alpha1.ArgusWatcher) (result *v1alpha1.ArgusWatcher, err error) {
	result = &v1alpha1.ArgusWatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("arguswatchers").
		Name(argusWatcher.Name).
		Body(argusWatcher).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *argusWatchers) UpdateStatus(argusWatcher *v1alpha1.ArgusWatcher) (result *v1alpha1.ArgusWatcher, err error) {
	result = &v1alpha1.ArgusWatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("arguswatchers").
		Name(argusWatcher.Name).
		SubResource("status").
		Body(argusWatcher).
		Do().
		Into(result)
	return
}

// Delete takes name of the argusWatcher and deletes it. Returns an error if one occurs.
func (c *argusWatchers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("arguswatchers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *argusWatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("arguswatchers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched argusWatcher.
func (c *argusWatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArgusWatcher, err error) {
	result = &v1alpha1.ArgusWatcher{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("arguswatchers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
