// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	arguscontrollerv1alpha1 "clustergarage.io/argus-controller/pkg/apis/arguscontroller/v1alpha1"
	versioned "clustergarage.io/argus-controller/pkg/client/clientset/versioned"
	internalinterfaces "clustergarage.io/argus-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "clustergarage.io/argus-controller/pkg/client/listers/arguscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArgusWatcherInformer provides access to a shared informer and lister for
// ArgusWatchers.
type ArgusWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ArgusWatcherLister
}

type argusWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArgusWatcherInformer constructs a new informer for ArgusWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewArgusWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredArgusWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredArgusWatcherInformer constructs a new informer for ArgusWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredArgusWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArguscontrollerV1alpha1().ArgusWatchers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArguscontrollerV1alpha1().ArgusWatchers(namespace).Watch(options)
			},
		},
		&arguscontrollerv1alpha1.ArgusWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *argusWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredArgusWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *argusWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&arguscontrollerv1alpha1.ArgusWatcher{}, f.defaultInformer)
}

func (f *argusWatcherInformer) Lister() v1alpha1.ArgusWatcherLister {
	return v1alpha1.NewArgusWatcherLister(f.Informer().GetIndexer())
}
