// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "clustergarage.io/argus-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ArgusWatchers returns a ArgusWatcherInformer.
	ArgusWatchers() ArgusWatcherInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ArgusWatchers returns a ArgusWatcherInformer.
func (v *version) ArgusWatchers() ArgusWatcherInformer {
	return &argusWatcherInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
