// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	fimcontroller_v1alpha1 "clustergarage.io/fim-controller/pkg/apis/fimcontroller/v1alpha1"
	versioned "clustergarage.io/fim-controller/pkg/client/clientset/versioned"
	internalinterfaces "clustergarage.io/fim-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "clustergarage.io/fim-controller/pkg/client/listers/fimcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FimWatcherInformer provides access to a shared informer and lister for
// FimWatchers.
type FimWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.FimWatcherLister
}

type fimWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFimWatcherInformer constructs a new informer for FimWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFimWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFimWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFimWatcherInformer constructs a new informer for FimWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFimWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FimcontrollerV1alpha1().FimWatchers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FimcontrollerV1alpha1().FimWatchers(namespace).Watch(options)
			},
		},
		&fimcontroller_v1alpha1.FimWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *fimWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFimWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *fimWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fimcontroller_v1alpha1.FimWatcher{}, f.defaultInformer)
}

func (f *fimWatcherInformer) Lister() v1alpha1.FimWatcherLister {
	return v1alpha1.NewFimWatcherLister(f.Informer().GetIndexer())
}
