// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "clustergarage.io/fim-k8s/pkg/apis/fimcontroller/v1alpha1"
	scheme "clustergarage.io/fim-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FimListenersGetter has a method to return a FimListenerInterface.
// A group's client should implement this interface.
type FimListenersGetter interface {
	FimListeners(namespace string) FimListenerInterface
}

// FimListenerInterface has methods to work with FimListener resources.
type FimListenerInterface interface {
	Create(*v1alpha1.FimListener) (*v1alpha1.FimListener, error)
	Update(*v1alpha1.FimListener) (*v1alpha1.FimListener, error)
	UpdateStatus(*v1alpha1.FimListener) (*v1alpha1.FimListener, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FimListener, error)
	List(opts v1.ListOptions) (*v1alpha1.FimListenerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimListener, err error)
	FimListenerExpansion
}

// fimListeners implements FimListenerInterface
type fimListeners struct {
	client rest.Interface
	ns     string
}

// newFimListeners returns a FimListeners
func newFimListeners(c *FimcontrollerV1alpha1Client, namespace string) *fimListeners {
	return &fimListeners{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fimListener, and returns the corresponding fimListener object, and an error if there is any.
func (c *fimListeners) Get(name string, options v1.GetOptions) (result *v1alpha1.FimListener, err error) {
	result = &v1alpha1.FimListener{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimlisteners").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FimListeners that match those selectors.
func (c *fimListeners) List(opts v1.ListOptions) (result *v1alpha1.FimListenerList, err error) {
	result = &v1alpha1.FimListenerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimlisteners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fimListeners.
func (c *fimListeners) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fimlisteners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fimListener and creates it.  Returns the server's representation of the fimListener, and an error, if there is any.
func (c *fimListeners) Create(fimListener *v1alpha1.FimListener) (result *v1alpha1.FimListener, err error) {
	result = &v1alpha1.FimListener{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fimlisteners").
		Body(fimListener).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fimListener and updates it. Returns the server's representation of the fimListener, and an error, if there is any.
func (c *fimListeners) Update(fimListener *v1alpha1.FimListener) (result *v1alpha1.FimListener, err error) {
	result = &v1alpha1.FimListener{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimlisteners").
		Name(fimListener.Name).
		Body(fimListener).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fimListeners) UpdateStatus(fimListener *v1alpha1.FimListener) (result *v1alpha1.FimListener, err error) {
	result = &v1alpha1.FimListener{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimlisteners").
		Name(fimListener.Name).
		SubResource("status").
		Body(fimListener).
		Do().
		Into(result)
	return
}

// Delete takes name of the fimListener and deletes it. Returns an error if one occurs.
func (c *fimListeners) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimlisteners").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fimListeners) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimlisteners").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fimListener.
func (c *fimListeners) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimListener, err error) {
	result = &v1alpha1.FimListener{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fimlisteners").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
