// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "clustergarage.io/fim-k8s/pkg/apis/fimcontroller/v1alpha1"
	scheme "clustergarage.io/fim-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FimWatchesGetter has a method to return a FimWatchInterface.
// A group's client should implement this interface.
type FimWatchesGetter interface {
	FimWatches(namespace string) FimWatchInterface
}

// FimWatchInterface has methods to work with FimWatch resources.
type FimWatchInterface interface {
	Create(*v1alpha1.FimWatch) (*v1alpha1.FimWatch, error)
	Update(*v1alpha1.FimWatch) (*v1alpha1.FimWatch, error)
	UpdateStatus(*v1alpha1.FimWatch) (*v1alpha1.FimWatch, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FimWatch, error)
	List(opts v1.ListOptions) (*v1alpha1.FimWatchList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatch, err error)
	FimWatchExpansion
}

// fimWatches implements FimWatchInterface
type fimWatches struct {
	client rest.Interface
	ns     string
}

// newFimWatches returns a FimWatches
func newFimWatches(c *FimcontrollerV1alpha1Client, namespace string) *fimWatches {
	return &fimWatches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fimWatch, and returns the corresponding fimWatch object, and an error if there is any.
func (c *fimWatches) Get(name string, options v1.GetOptions) (result *v1alpha1.FimWatch, err error) {
	result = &v1alpha1.FimWatch{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimwatches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FimWatches that match those selectors.
func (c *fimWatches) List(opts v1.ListOptions) (result *v1alpha1.FimWatchList, err error) {
	result = &v1alpha1.FimWatchList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimwatches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fimWatches.
func (c *fimWatches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fimwatches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fimWatch and creates it.  Returns the server's representation of the fimWatch, and an error, if there is any.
func (c *fimWatches) Create(fimWatch *v1alpha1.FimWatch) (result *v1alpha1.FimWatch, err error) {
	result = &v1alpha1.FimWatch{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fimwatches").
		Body(fimWatch).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fimWatch and updates it. Returns the server's representation of the fimWatch, and an error, if there is any.
func (c *fimWatches) Update(fimWatch *v1alpha1.FimWatch) (result *v1alpha1.FimWatch, err error) {
	result = &v1alpha1.FimWatch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimwatches").
		Name(fimWatch.Name).
		Body(fimWatch).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fimWatches) UpdateStatus(fimWatch *v1alpha1.FimWatch) (result *v1alpha1.FimWatch, err error) {
	result = &v1alpha1.FimWatch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimwatches").
		Name(fimWatch.Name).
		SubResource("status").
		Body(fimWatch).
		Do().
		Into(result)
	return
}

// Delete takes name of the fimWatch and deletes it. Returns an error if one occurs.
func (c *fimWatches) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimwatches").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fimWatches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimwatches").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fimWatch.
func (c *fimWatches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatch, err error) {
	result = &v1alpha1.FimWatch{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fimwatches").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
