// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "clustergarage.io/fim-controller/pkg/apis/fimcontroller/v1alpha1"
	scheme "clustergarage.io/fim-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FimWatchersGetter has a method to return a FimWatcherInterface.
// A group's client should implement this interface.
type FimWatchersGetter interface {
	FimWatchers(namespace string) FimWatcherInterface
}

// FimWatcherInterface has methods to work with FimWatcher resources.
type FimWatcherInterface interface {
	Create(*v1alpha1.FimWatcher) (*v1alpha1.FimWatcher, error)
	Update(*v1alpha1.FimWatcher) (*v1alpha1.FimWatcher, error)
	UpdateStatus(*v1alpha1.FimWatcher) (*v1alpha1.FimWatcher, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FimWatcher, error)
	List(opts v1.ListOptions) (*v1alpha1.FimWatcherList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatcher, err error)
	FimWatcherExpansion
}

// fimWatchers implements FimWatcherInterface
type fimWatchers struct {
	client rest.Interface
	ns     string
}

// newFimWatchers returns a FimWatchers
func newFimWatchers(c *FimcontrollerV1alpha1Client, namespace string) *fimWatchers {
	return &fimWatchers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fimWatcher, and returns the corresponding fimWatcher object, and an error if there is any.
func (c *fimWatchers) Get(name string, options v1.GetOptions) (result *v1alpha1.FimWatcher, err error) {
	result = &v1alpha1.FimWatcher{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimwatchers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FimWatchers that match those selectors.
func (c *fimWatchers) List(opts v1.ListOptions) (result *v1alpha1.FimWatcherList, err error) {
	result = &v1alpha1.FimWatcherList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fimwatchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fimWatchers.
func (c *fimWatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fimwatchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fimWatcher and creates it.  Returns the server's representation of the fimWatcher, and an error, if there is any.
func (c *fimWatchers) Create(fimWatcher *v1alpha1.FimWatcher) (result *v1alpha1.FimWatcher, err error) {
	result = &v1alpha1.FimWatcher{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fimwatchers").
		Body(fimWatcher).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fimWatcher and updates it. Returns the server's representation of the fimWatcher, and an error, if there is any.
func (c *fimWatchers) Update(fimWatcher *v1alpha1.FimWatcher) (result *v1alpha1.FimWatcher, err error) {
	result = &v1alpha1.FimWatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimwatchers").
		Name(fimWatcher.Name).
		Body(fimWatcher).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fimWatchers) UpdateStatus(fimWatcher *v1alpha1.FimWatcher) (result *v1alpha1.FimWatcher, err error) {
	result = &v1alpha1.FimWatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fimwatchers").
		Name(fimWatcher.Name).
		SubResource("status").
		Body(fimWatcher).
		Do().
		Into(result)
	return
}

// Delete takes name of the fimWatcher and deletes it. Returns an error if one occurs.
func (c *fimWatchers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimwatchers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fimWatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fimwatchers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fimWatcher.
func (c *fimWatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FimWatcher, err error) {
	result = &v1alpha1.FimWatcher{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fimwatchers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
