// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "clustergarage.io/argus-controller/pkg/client/clientset/versioned/typed/arguscontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeArguscontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeArguscontrollerV1alpha1) ArgusWatchers(namespace string) v1alpha1.ArgusWatcherInterface {
	return &FakeArgusWatchers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeArguscontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
