kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: fim-scc
  namespace: kube-system
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- fim-admin
groups:
- fim-group
- system:cluster-admins
- system:nodes
- system:masters
allowedCapabilities:
- '*'
volumes:
- '*'
